# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 703)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_edit.setObjectName("lineEdit_edit")
        self.verticalLayout.addWidget(self.lineEdit_edit)
        self.lineEdit_display = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_display.setEnabled(False)
        self.lineEdit_display.setReadOnly(True)
        self.lineEdit_display.setClearButtonEnabled(False)
        self.lineEdit_display.setObjectName("lineEdit_display")
        self.verticalLayout.addWidget(self.lineEdit_display)
        self.spinBox_edit = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_edit.setObjectName("spinBox_edit")
        self.verticalLayout.addWidget(self.spinBox_edit)
        self.spinBox_display = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_display.setEnabled(False)
        self.spinBox_display.setAutoFillBackground(False)
        self.spinBox_display.setReadOnly(True)
        self.spinBox_display.setObjectName("spinBox_display")
        self.verticalLayout.addWidget(self.spinBox_display)
        self.pushButton_run = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_run.setObjectName("pushButton_run")
        self.verticalLayout.addWidget(self.pushButton_run)
        self.pushButton_plot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.verticalLayout.addWidget(self.pushButton_plot)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MplWidget_left = MplWidget(self.centralwidget)
        self.MplWidget_left.setMinimumSize(QtCore.QSize(480, 480))
        self.MplWidget_left.setObjectName("MplWidget_left")
        self.horizontalLayout.addWidget(self.MplWidget_left)
        self.MplWidget_right = MplWidget(self.centralwidget)
        self.MplWidget_right.setMinimumSize(QtCore.QSize(480, 480))
        self.MplWidget_right.setObjectName("MplWidget_right")
        self.horizontalLayout.addWidget(self.MplWidget_right)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_edit.setText(_translate("MainWindow", "Enter here some text"))
        self.pushButton_run.setText(_translate("MainWindow", "run script (See terminal output)"))
        self.pushButton_plot.setText(_translate("MainWindow", "plot data"))
from sampleCode.gui.mplwidget import MplWidget
