# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 781, 541))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox_edit = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_edit.setObjectName("spinBox_edit")
        self.gridLayout.addWidget(self.spinBox_edit, 2, 1, 1, 1)
        self.MplWidget = MplWidget(self.gridLayoutWidget)
        self.MplWidget.setMinimumSize(QtCore.QSize(480, 320))
        self.MplWidget.setObjectName("MplWidget")
        self.gridLayout.addWidget(self.MplWidget, 6, 1, 1, 1)
        self.lineEdit_display = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_display.setEnabled(False)
        self.lineEdit_display.setReadOnly(True)
        self.lineEdit_display.setClearButtonEnabled(False)
        self.lineEdit_display.setObjectName("lineEdit_display")
        self.gridLayout.addWidget(self.lineEdit_display, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 1, 1, 1)
        self.pushButton_run = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_run.setObjectName("pushButton_run")
        self.gridLayout.addWidget(self.pushButton_run, 4, 1, 1, 1)
        self.pushButton_plot = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.gridLayout.addWidget(self.pushButton_plot, 5, 1, 1, 1)
        self.lineEdit_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_edit.setObjectName("lineEdit_edit")
        self.gridLayout.addWidget(self.lineEdit_edit, 0, 1, 1, 1)
        self.spinBox_display = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_display.setEnabled(False)
        self.spinBox_display.setAutoFillBackground(False)
        self.spinBox_display.setReadOnly(True)
        self.spinBox_display.setObjectName("spinBox_display")
        self.gridLayout.addWidget(self.spinBox_display, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_run.setText(_translate("MainWindow", "run script"))
        self.pushButton_plot.setText(_translate("MainWindow", "plot data"))
        self.lineEdit_edit.setText(_translate("MainWindow", "Enter here some text"))
from sampleCode.gui.mplwidget import MplWidget
